### ISSUE TITLE
Projects not listing

### ISSUE THREAD

**Issue by m-tranter** [contensis/node-cli#1]
Hi,

I have been trying to use Contensis cli. Although I can login and connect to my environment, no projects are listed.

![09-11](https://user-images.githubusercontent.com/6093668/222681281-50b97fed-0c99-4ef6-bb37-47cc6b5eda2b.png)

**Comment by m-tranter** [comment]
Hi, I have made some progress but I get this error:
Error: 14:45:08] [ERROR] Error: Error loading shared library libsecret-1.so.0: No such file or directory (needed by /usr/src/app/node_modules/keytar/build/Release/keytar.node)

I am using Ubuntu in github & libsecret is installed.

**Comment by nflatley-zengenti** [comment]
Hi Mark,
Apologies for the delayed reply I have been recently working on this project and noticed the open issue.

The error states it could not find the necessary binary to access a secret store on your system

Most systems with a desktop environment will already have access to a keystore/keychain/credential manager

There is a note in the readme regarding running the cli on headless systems.

https://github.com/contensis/node-cli/blob/main/packages/contensis-cli/README.md#running-headless

You may wish to try the commands to install and unlock a secret store in your terminal instance

If this is a temporary / throwaway environment, you can also bypass all of this by supplying the password in plain text when logging in e.g. `login m.tranter -pw yourpassword` (you will see a warning that this is not secure)

Kind regards
Neil
